openapi: 3.0.0
info:
  version: 1.0.0
  title: smartAPI
  description: This is smartAPI
servers:
  - url: 'https://us-central1-smartapi-295619.cloudfunctions.net/DigiCertApttusWS_CF/getcontract'
paths:
  '/id/{userId}/name/{name}':
    get:
      summary: Returns a user by ID
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return
          schema:
            type: string
        - name: name
          in: path
          required: true
          description: The Name of the contract
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  contract:
                    type: object
                    properties:
                      type:
                        type: string
                      adjustment:
                        type: string
                      overall_discount_percent:
                        type: number
                      total_size:
                        type: number
                      entitlements:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - product_id
                            - product_name
                            - term
                            - currency
                            - list_price
                            - discount_price
                            - discount_percent
                          properties:
                            product_id:
                              type: string
                              minLength: 1
                            product_name:
                              type: string
                              minLength: 1
                            term:
                              type: string
                              minLength: 1
                            currency:
                              type: string
                              minLength: 1
                            list_price:
                              type: number
                            discount_price:
                              type: number
                            discount_percent:
                              type: number
                    required:
                      - type
                      - adjustment
                      - overall_discount_percent
                      - total_size
                      - entitlements
                  time_to_run:
                    type: string
                    minLength: 1
                required:
                  - contract
                  - time_to_run
              examples:
                example-1:
                  value:
                    contract:
                      type: string
                      adjustment: string
                      overall_discount_percent: 0
                      total_size: 0
                      entitlements:
                        - product_id: string
                          product_name: string
                          term: string
                          currency: string
                          list_price: 0
                          discount_price: 0
                          discount_percent: 0
                    time_to_run: string
        '400':
          description: The specified user ID is invalid (e.g. not a number)
        '404':
          description: A user with the specified ID was not found
      operationId: ''
      description: ''
    parameters: []
